### ISSUE TITLE
Searx?

### ISSUE THREAD

**Issue by PwnArt1st** [duckduckgo/safari-zeroclickinfo#10]
Is [searx](searx.me) support possible? Searx already as a plugin api so I hope it wouldnt be too hard.

**Comment by mrshu** [comment]
Hey @PwnArt1st, thanks for the suggestion.

How would you like this integration to work? I do not quite get that to be honest.

**Comment by PwnArt1st** [comment]
So sorry, believe I misinterpreted the function of the extension!
